title: Welcome Onboard Guys 
author: Thiyunu
email: Thiyunujayawickrama1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
      Heloo guys! My name is Thiyunu. Im under graduate from UOC.
      Glad to Know all of you!
      Cheers!

# social links
twitter_username: thiyunujk # DO NOT include the @ character, or else the build will fail!
github_username:  thiyunuJk # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
